### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by hamzah** [Lockna/qobuz-rpc#2]
Hi there,
I've been trying to install qobuz-rpc on my Mac but it doesn't seem to work due to its dependency on pywin32/win32gui. Could we see support for MacOS and Linux in the future?

**Comment by Lockna** [comment]
Due to school and work I unfortunately don't have time to get it running on MacOS and/or Linux. Sorry for that.
But of course I am open for pull requests and reviewing them.
